name: Make Packages on Push

on:
  push:
  pull_request:

jobs:
  make-package:
    strategy:
      matrix:
        package:
          - org.vrcau.vpm.systems.flight-menu
          - org.vrcau.vpm.systems.flight-menu.integration.sacc-flight-dfunc
          - org.vrcau.vpm.systems.flight-menu.integration.urc-redux

    uses: ./.github/workflows/make-package.yml
    with:
      ref: ${{ github.sha }}
      package: ${{ matrix.package }}
